spring:
  datasource:
    url: jdbc:mysql://129.204.119.180:8000/test?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ccq1994
  main:
    banner-mode: off
logging:
  level:
    com.example.demo: debug
