spring:
  datasource:
    url: jdbc:mysql://localhost:3306/re_blog?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  main:
    banner-mode: off
logging:
  level:
    com.example.demo: debug
